NoteBook/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth.views import PasswordResetView,PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tinymce/',include('tinymce.urls')),
    path('password-reset/',PasswordResetView.as_view(template_name='main/password_reset.html'),name='password_reset'),
    path('password-reset/done/',PasswordResetDoneView.as_view(template_name='main/password_reset_done.html'),name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',PasswordResetConfirmView.as_view(template_name='main/password_reset_confirm.html'),name='password_reset_confirm'),
    path('password-reset-complete/',PasswordResetCompleteView.as_view(template_name='main/password_reset_complete.html'),name='password_reset_complete'),
    path('webpush/', include('webpush.urls'),name='webpush'),
    path('', include("main.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path,include
from django.conf.urls import url
from django.views.generic import TemplateView
from . import views
app_name = "main"

urlpatterns = [
    path('', views.homepage, name = "homepage"),
    path('register/',views.register,name = 'register'),
    path('logout/',views.logout_request,name = 'logout'),
    path('login/',views.login_request,name= 'login'),
    path('account/',views.account,name='account'),
    path('account/edit/', views.edit_profile, name='edit_profile'),
	path('change_password/', views.change_password, name='change_password'),
	path('activate/<uidb64>/<token>/',views.activate,name='activate'),
	path('search/',views.search,name='search'),
	path('send_push/', views.send_push,name='send_push'),
	path('push-notifications/',views.push_notifications,name='push_notifications'),
    path('sw.js', TemplateView.as_view(template_name='sw.js', content_type='application/x-javascript')),
    path('<single_slug>/',views.single_slug,name= 'single_slug'),
	]

main/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.db.models.signals import post_save
# Create your models here.

class UserProfile(models.Model):
    user = models.OneToOneField(User,on_delete = models.SET_DEFAULT,default='')
    description = models.CharField(max_length=100, default='', blank=True)
    city = models.CharField(max_length=100, default='', blank=True)
    website = models.URLField(default='', blank=True)
    phone = models.IntegerField(default=0, blank=True)
    image = models.URLField(default='', blank=True)

    def __str__(self):
        return self.user.username

def create_profile(sender, **kwargs):
    if kwargs['created']:
        user_profile = UserProfile.objects.create(user=kwargs['instance'])

post_save.connect(create_profile, sender=User)


class NoteCategory(models.Model):
    note_category = models.CharField(max_length=200)
    category_summary = models.CharField(max_length=200)
    category_slug = models.CharField(max_length=200, default=1)
    
    CATEGORY_PIC = [ ('classwork','Class Work!'),('projectwork','Project Work!'),('labwork','Laboratory Work'),('explore','Explore the world!')]
    category_image = models.CharField(max_length=50,choices = CATEGORY_PIC, default = 'classwork')
    class Meta:
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.note_category

class NoteSeries(models.Model):
    note_series = models.CharField(max_length=200)
    note_category = models.ForeignKey(NoteCategory, default=1, verbose_name="Category", on_delete=models.SET_DEFAULT)
    series_summary = models.CharField(max_length=200)
    series_image = models.TextField(default = 'https://source.unsplash.com/random/400x350')
    class Meta:
        verbose_name_plural = "Series"

    def __str__(self):
        return self.note_series

class Note(models.Model):
	note_title = models.CharField(max_length = 250)
	note_content = models.TextField(default = "")
	note_published = models.DateTimeField("date published",default = timezone.now())
	note_series = models.ForeignKey(NoteSeries, default=1, verbose_name="Series", on_delete=models.SET_DEFAULT)
	note_slug = models.CharField(max_length=200, default=1)
	
	def __str__(self):
		return self.note_title
		

main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from .models import UserProfile

class NewUserForm(UserCreationForm):
	email = forms.EmailField(required = True)
	
	class Meta:
		model = User
		fields = ('username','email','password1','password2')
		
	def save(self,commit = True):
		user = super(NewUserForm, self).save(commit = False)
		user.email = self.cleaned_data['email']
		if commit:
			user.save()
		return user
		
class EditProfileForm(UserChangeForm):
    template_name='/something/else'
    class Meta:
        model = User
        fields = (
            'first_name',
            'last_name',
            'password'
			)
			
class EditUserProfileForm(UserChangeForm):
    template_name='/something/else'
    description = forms.CharField(max_length=350,required=False)
    city = forms.CharField(max_length=200,required=False)
    website = forms.URLField(required=False)
    phone = forms.IntegerField(required=False)
    image = forms.URLField(required=False)
    class Meta:
        model = UserProfile
        fields = (
            'description',
            'city',
            'website',
            'phone',
            'image',
			)

main/views.py
import re
import json

from django.shortcuts import render, redirect, get_object_or_404
from .models import NoteCategory, NoteSeries, Note
from django.contrib.auth.forms import  AuthenticationForm, PasswordChangeForm
from django.contrib.auth import login, logout, authenticate
from django.contrib import messages
from .forms import NewUserForm, EditProfileForm, EditUserProfileForm
from django.http import HttpResponse,JsonResponse
from django.urls import reverse
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.models import User
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from .tokens import account_activation_token
from django.core.mail import EmailMessage
from django.views.decorators.http import require_POST
from django.views.decorators.csrf import csrf_exempt
from webpush import send_user_notification
# Create your views here.

def single_slug(request,single_slug):
	category_slugs = [c.category_slug for c in NoteCategory.objects.all()]
	if single_slug in category_slugs:
		matching_series = NoteSeries.objects.filter(note_category__category_slug = single_slug)
		series_urls = {}
		for m in matching_series:
			part_one = Note.objects.filter(note_series__note_series = m.note_series).earliest('note_published')
			series_urls[m] = part_one.note_slug
		return render(request = request,
								template_name = 'main/category.html',
								context = {'note_series':matching_series,'part_ones':series_urls})		
	note_slugs = [n.note_slug for n in Note.objects.all()]
	if single_slug in note_slugs:
		this_note = Note.objects.get(note_slug=single_slug)
		notes_from_series = Note.objects.filter(note_series__note_series=this_note.note_series).order_by('note_published')
		this_note_index = list(notes_from_series).index(this_note)
		
		return render(request=request,
                      template_name='main/note.html',
                      context={"note": this_note,
									   "sidebar": notes_from_series,
									   "index": this_note_index})
	return HttpResponse(f'{single_slug} corresponds to nothing')

def search(request):
	if request.method != 'POST':
		return redirect('main:homepage')
	stop_words = ["a", "able", "about", "across", "after", "all", "almost", "also", "am", "among", "an", "and", "any", "are", "as", "at", "be", "because", "been", "but", "by", "can", "cannot", "could", "dear", "did", "do", "does", "either", "else", "ever", "every", "for", "from", "get", "got", "had", "has", "have", "he", "her", "hers", "him", "his", "how", "however", "i", "if", "in", "into", "is", "it", "its", "just", "least", "let", "like", "likely", "may", "me", "might", "most", "must", "my", "neither", "no", "nor", "not", "of", "off", "often", "on", "only", "or", "other", "our", "own", "rather", "said", "say", "says", "she", "should", "since", "so", "some", "than", "that", "the", "their", "them", "then", "there", "these", "they", "this", "tis", "to", "too", "twas", "us", "wants", "was", "we", "were", "what", "when", "where", "which", "while", "who", "whom", "why", "will", "with", "would", "yet", "you", "your", "ain't", "aren't", "can't", "could've", "couldn't", "didn't", "doesn't", "don't", "hasn't", "he'd", "he'll", "he's", "how'd", "how'll", "how's", "i'd", "i'll", "i'm", "i've", "isn't", "it's", "might've", "mightn't", "must've", "mustn't", "shan't", "she'd", "she'll", "she's", "should've", "shouldn't", "that'll", "that's", "there's", "they'd", "they'll", "they're", "they've", "wasn't", "we'd", "we'll", "we're", "weren't", "what'd", "what's", "when'd", "when'll", "when's", "where'd", "where'll", "where's", "who'd", "who'll", "who's", "why'd", "why'll", "why's", "won't", "would've", "wouldn't", "you'd", "you'll", "you're", "you've","learnt","learn"]
	keys = request.POST.get('search')
	keys = re.split('\W+',keys)
	valid_keys = []
	for key in keys:
		if len(key) > 3 and key not in stop_words:
			valid_keys.append(key.lower())
	valid_keys.extend(['c++','c'])
	print(valid_keys)
	matching_series = {}
	matching_notes = {}
	for key in valid_keys:
		series = list(NoteSeries.objects.all())
		for s in series:
			a = str(s.note_series).lower().split()  + str(s.series_summary).lower().split()
			if key in a :
				matching_series[s.note_series] = s
		notes = list(Note.objects.all())
		for n in notes:
			b = str(n.note_title).lower().split()
			if key in b:
				matching_notes[n.note_title] = n		
	
		series_urls = {}
		for m in matching_series:
			part_one = Note.objects.filter(note_series__note_series = m).earliest('note_published')
			series_urls[matching_series[m]] = part_one.note_slug
	messages.warning(request,"Search is in alpha mode...So keep your expectations low :)" )
	return render(request = request,
							template_name = 'main/search.html',
							context = {'matching_series':matching_series,'matching_notes':matching_notes,'part_ones':series_urls,'no_series':len(matching_series) == 0,'no_note':len(matching_notes) == 0})

def homepage(request):
	return render(request = request,
							template_name = 'main/categories.html',
							context={"categories":NoteCategory.objects.all})


def account(request):
	return render(request = request,
							template_name = 'main/account.html',
							context = {'user':request.user})	


def register(request):
	if request.method == 'POST':
		form = NewUserForm(request.POST)
		if form.is_valid():
			to_email = form.cleaned_data.get('email')
			already_registered = User.objects.filter(email = to_email)
			if len(already_registered) >= 1:
				messages.error(request,'The email is already in use.')
				return redirect("main:register")


			user = form.save(commit = False)
			user.is_active = False
			user.save()
			current_site = get_current_site(request)
			mail_subject = 'Activate your NoteBook account.'
			message = render_to_string('main/acc_active_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid':urlsafe_base64_encode(force_bytes(user.pk)),#.decode(),
                'token':account_activation_token.make_token(user),
            })
			email = EmailMessage(mail_subject, message, to=[to_email])
			email.send()
			messages.info(request,f'Verification link sent!')
			return render(request = request,
									  template_name = 'main/confirm_email.html',
									  context = {})
		else:
			for msg in form.error_messages:
				messages.error(request, f"{msg}: {form.error_messages[msg]}")
	
	form = NewUserForm()	
	
	return render(request = request,
							template_name = 'main/register.html',
							context = {"form":form})

def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        username = user.username
        messages.success(request, f"New account created: {username}")
        login(request, user)
        messages.info(request, f'You are now logged in as {username}')
        return redirect("main:homepage")
    else:
        return HttpResponse('Activation link is invalid!')


def logout_request(request):
	logout(request)
	messages.info(request,'Logged out successfully!')
	return redirect('main:login')


def edit_profile(request):
    if request.method == 'POST':
        form = EditProfileForm(request.POST, instance=request.user)
        form2 = EditUserProfileForm(request.POST,request.FILES,instance = request.user.userprofile)
        if form.is_valid() and form2.is_valid():
            form.save()
            form2.save()
            print(form2.cleaned_data.get('image'))
            return redirect(reverse('main:account'))
    else:
        form = EditProfileForm(instance=request.user)
        form2 = EditUserProfileForm(instance = request.user.userprofile)
    return render(request = request,
							template_name = 'main/edit_profile.html',
							context = {'form': form,'form2':form2})


def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)

        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect(reverse('main:account'))
        else:
            return redirect(reverse('main:change_password'))
    else:
        form = PasswordChangeForm(user=request.user)
    return render(request = request, 
							template_name = 'main/change_password.html', 
							context = {'form': form})

def login_request(request):
	if request.method == 'POST':
		form = AuthenticationForm(request, data = request.POST)
		if form.is_valid():
			username = form.cleaned_data.get('username') 
			password = form.cleaned_data.get('password')
			user = authenticate(username = username,password = password)
			if user is not None:
				login(request,user)
				messages.info(request, f'You are logged in as {username}')
				return redirect('main:homepage')
			else:
				messages.error(request, 'Invalid username or password')
		else:
				messages.error(request, 'Invalid username or password')
	
	form = AuthenticationForm
	return render(request = request,
							template_name = 'main/login.html',
							context = {'form' : form})
							
@require_POST
@csrf_exempt
def send_push(request):
    try:
        body = request.body
        data = json.loads(body)

        if 'head' not in data and 'body' not in data and 'id' not in data:
            return JsonResponse(status=400, data={"message": "Invalid data format"})
        user_id = data['id']
        user = get_object_or_404(User, pk=user_id)

main/templates/main/acc_active_email.html
{% autoescape off %}
Hi {{ user.username }},
Please click on the link to confirm your registration,http://{{ domain }}{% url 'main:activate' uidb64=uid token=token %}
{% endautoescape %}

main/templates/main/account.html
{% extends 'main/header.html' %}

{% load static %}
{% block content %}
		  
		  
		  <div style="display: flex;flex-wrap: wrap;justify-content: space-between;">
        <h2 class="section-title wow fadeInUp">About Me</h2>

        <div class="row" >

          <div class="col md12 l12 s12">
            <div class="biography">
              <div  style="max-width:415px;border-radius:50%;">
				  {% if user.userprofile.image != '' %}
				  			<img src="{{ user.userprofile.image }}"  style="width:100%;max-width: 600px;overflow: hidden;"alt="">
                {% else %}
                           <img src="{% static 'main/images/user.jpeg' %}" alt="" >
                {% endif %}
              </div>
              <ul class="collection">
                <li class="collection-item active"><strong>Username:</strong> {{ user }}</li>
                <li class="collection-item"><strong>Name:</strong> {{ user.first_name }} {{ user.last_name }}</li>
                <li class="collection-item"><strong>Email:</strong> {{ user.email }}</li>
                <li class="collection-item"><strong>City:</strong> {{ user.userprofile.city }}</li>
                <li class="collection-item"><strong>Nationality:</strong> Indian</li>
                <li class="collection-item"><strong>Phone:</strong> {{ user.userprofile.phone }}</li>
                <li class="collection-item"><strong>Website:</strong> {{ user.userprofile.website }}</li>
              </ul>
              <div class="card-action">
				  <a href="/account/edit" class="btn">Edit</a>
				</div>
            </div>
          </div> 


          </div>


        </div> <!-- /.row -->
      </div> <!-- /.container -->
		  

{% endblock %}

main/templates/main/categories.html
{% extends 'main/header.html' %}
{% load static %}
{% block content %}

    <div class="row">
        {% for cat in categories %}
            <div class="col s12 m6 l4">
                <a href="/{{cat.category_slug}}", style="color:#000">
                    <div class="card hoverable">
						<div class="card-image">
									  <img src="static/main/images/{{cat.category_image}}.jpg" >
									  <span class="card-title">{{cat.note_category}}</span>	  
						</div>
                        <div class="card-content">
                            <p>{{cat.category_summary}}</p>
                        </div>
                    </div>
                </a>
            </div>
        {% endfor %}
    </div>
    
  <script>

function urlB64ToUnit8Array(base64String) {
    const padding = '='.repeat((4 - base64String.length % 4) % 4);
    const base64 = (base64String + padding)
        .replace(/\-/g, '+')
        .replace(/_/g, '/');

    const rawData = window.atob(base64);
    const outputArray = new Uint8Array(rawData.length);
    const outputData = outputArray.map((output, index) => rawData.charCodeAt(index));

    return outputData;
}


const registerSw = async () => {
    if ('serviceWorker' in navigator) {
        const reg = await navigator.serviceWorker.register('sw.js');
        initialiseState(reg)

    } 
};


const initialiseState = (reg) => {
    if (!reg.showNotification) {
        return
    }
    if (Notification.permission === 'denied') {
        return
    }
    if (!'PushManager' in window) {
        return
    }
    subscribe(reg);
}

const subscribe = async (reg) => {
    const subscription = await reg.pushManager.getSubscription();
    if (subscription) {
        sendSubData(subscription);
        return;
    }

   const key = "BG9mp7rgU7s90iHGOq0eC99cJG6g3Ii4t8ev23rWUVPEjNVYAYpc-rK9qoCXrHcF-EGr5_zyGZDYzsdodRDhVTM";
    var options
    if(key){
        options = {
        userVisibleOnly: true,
        applicationServerKey: urlB64ToUnit8Array(key)
    }
	}
    else{
		options = {
			userVisibleOnly:true
		}
	}
	
    const sub = await reg.pushManager.subscribe(options);
    sendSubData(sub)
};

const sendSubData = async (subscription) => {
    const browser = navigator.userAgent.match(/(firefox|msie|chrome|safari|trident)/ig)[0].toLowerCase();
    const data = {
        status_type: 'subscribe',
        subscription: subscription.toJSON(),
        browser: browser,
    };

    const res = await fetch('/webpush/save_information', {
        method: 'POST',
        body: JSON.stringify(data),
        headers: {
            'content-type': 'application/json'
        },
        credentials: "include"
    });

    handleResponse(res);
};

const handleResponse = (res) => {
    console.log(res.status);
};

registerSw();
	
	</script>
{% endblock %}

main/templates/main/category.html
{% extends 'main/header.html' %}

{% block content %}

    <div class="row">
        {% for note, partone in part_ones.items %}

            <div class="col s12 m6 l4">
                <a href="/{{partone}}", style="color:#000">
                    <div class="card hoverable">
                        <div class="card-image">
									  <img src="{{note.series_image}}">
									  <span class="card-title">{{note.note_series}}</span>	  
						</div>
                        <div class="card-content">
						<br>
                            <p>{{note.series_summary}}</p>
                        </div>
                    </div>
                </a>
            </div>
        {% endfor %}
    </div>
{% endblock %}

main/templates/main/change_password.html
{% extends 'main/header.html' %}


{% block content %}
<div class="container">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class = 'btn' type="submit">Submit</button>
    </form>
    <br>
</div>

{% endblock %}

main/templates/main/confirm_email.html
{% extends 'main/header.html' %}
{% block content %}
	<div class="container">
		<h1>Email Verification link sent!</h1>
		<p>We've emailed you instructions for activating your account. You should receive them shortly.If you don't receive an email, please make sure you've entered the correct email address, and check your spam folder.</p>
	</div>
{% endblock %} 

main/templates/main/edit_profile.html
{% extends 'main/header.html' %}


{% block content %}
 <div id="overlay" class="invisible"></div> 
<div class="container">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class = "row">
        {% for field in form %}
			<div class="input-field col s12 m12 l12">
				{% if field.errors %}
				<p>{{ field.errors }}</p>
				{% endif %}
				{% if forloop.counter0 == 2 %}
				{{ field.label_tag }} <div class="spacer">{{field}}</div>
				{% else %}
				{{ field.label_tag }} {{field}}
				{% endif %}
			</div>
		{% endfor %}
		<br><br>
		{% for field in form2 %}
			<div class="input-field col s12 m12 l12">
				{% if field.errors %}
				<p>{{ field.errors }}</p>
				{% endif %}
				{% if forloop.counter0 == 4 %}
				{{ field.label_tag }} <div class="spacer destroy-css hide-me" style="display:none;">{{field}}</div>
				{% elif forloop.counter0 != 5 %}
				{{ field.label_tag }} {{field}}
				{% endif %}
			</div>
		{% endfor %}
		<div class="file-field input-field col s12 m12 l12" style="display:flex;">
						  <div class="btn btn-small purple">
							<label for="files" style="color:#fff;font-size:1em;"><span>Choose File</span></label>
							<input type="file" name="files[]" id="files" style="z-index: -1;">
						  </div>
						  <div class="file-path-wrapper" style="z-index: -1;">
							<input class="file-path validate" type="text">
						  </div>
						  <div>
						  <button type="button" class="btn green" onclick="uploadimage();">Upload</button>
						  </div>
				</div>
			  <div class="progress invisible" id="fieldB">
				  <div class="indeterminate"></div>
			  </div>
		</div>
		<p>Raw passwords are not stored, so there is no way to see this user’s password, but you can change the password using <a href="/change_password">this form</a>.</p>
        <button class='btn' type="submit">Submit</button>
    </form>
    <br>
</div>
<script src="https://www.gstatic.com/firebasejs/7.6.0/firebase-app.js"></script>
<script src="https://www.gstatic.com/firebasejs/7.6.0/firebase-storage.js"></script>

<script>
	document.getElementById("id_image").value = '';
	  var config = {
			'apiKey': "AIzaSyCTGc0x8acUhHq5iM3bNI2GYbQYal4czps",
			'authDomain': "notebook-aca9b.firebaseapp.com",
			'databaseURL': "https://notebook-aca9b.firebaseio.com",
			'projectId': "notebook-aca9b",
			'storageBucket': "notebook-aca9b.appspot.com",
			'messagingSenderId': "634156586246",
			'appId': "1:634156586246:web:0e5ce1b8f72928d6d0fa87",
			'measurementId': "G-RLR7491Z7P"
			}
	  firebase.initializeApp(config);
	  
	  function uploadimage(){
			  
			  var storage = firebase.storage();
			  var file = document.getElementById("files").files[0];
			  if(file == undefined){
				  alert("Please choose a file or leave the field as it is");
				  return;
			  }
			  if(file.type.substring(0,5) != 'image'){
				  alert("Invalid File Format !!");
				  return;
			  }
			  if(file.size >= 1024*1024 ){
				  alert("Size file should be less than 1 Mb!")
				  return;
			  }
			  document.getElementById('overlay').classList.remove("invisible")
			  document.getElementById('fieldB').classList.remove("invisible")
			  var storageRef = storage.ref();
			  var thisref = storageRef.child('profile_images/{{user.username}}').put(file);
			  thisref.on('state_changed',function(snapshot){
			  },
			  function(error) {
				  document.getElementById('fieldA').classList.add("invisible");
			      document.getElementById('fieldB').classList.add("invisible");
			      alert("Image Upload Failed!!")
			  },
			  function() {
			    thisref.snapshot.ref.getDownloadURL().then(function(downloadURL) {
							console.log('File available at', downloadURL);
							document.getElementById("id_image").value = downloadURL;
							alert("Image Uploaded Successfully!!");
							document.getElementById('overlay').classList.add("invisible");
							document.getElementById('fieldB').classList.add("invisible");
			   });
			});
	  }
</script>

{% endblock %}

main/templates/main/header.html
{% load static %}
<head>
	<meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% if user.id %}
        <meta name="user_id" content="{{ user.id }}">
    {% endif %}
	<link href="{% static 'tinymce/css/prism.css' %}" rel='stylesheet'>
	<link rel="shortcut icon" type="image/png" href="{% static 'main/images/icons/Icon-48.png' %}"/>
	<link href="{% static 'main/css/styles.css' %}" rel='stylesheet'>
	 <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
	<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
	 <link rel="manifest" href="{% static 'main/manifest.webmanifest' %}">
</head>
<body> 
	{% include 'main/includes/navbar.html'%}
    {% include 'main/includes/messages.html'%}
	 <div class='container'>
		 <br><br>
	 {% block content %}
	 {% endblock %}
	 </div>
	<script src="{% static 'tinymce/js/prism.js' %}"></script>
	<script>M.AutoInit();</script>
</body>

main/templates/main/home.html
{% extends 'main/header.html' %}
 {% block content %}
	 <div class="row">
		{% for note in notes %}
		<div class="col s12 m6 l4">
			  <div class="card blue-grey darken-1">
				<div class="card-content white-text">
				  <span class="card-title">{{note.note_title}}</span>
				  <p style='font-size:70%'>{{note.note_published}}</p>
				  <p>{{note.note_content|safe}}</p>
				</div>
			  </div>
		</div>
		{% endfor %}
	</div>
	{% endblock %}

main/templates/main/password_reset.html
{% extends 'main/header.html' %}


{% block content %}
<div class="container">
    <h1>Password reset</h1>
    <p>
        Forgotten your password? Enter your email address below, and we'll email instructions for setting a new one.
    </p>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn">Reset password</button>
    </form>
</div>
{% endblock %}

main/templates/main/password_reset_confirm.html
{% extends 'main/header.html' %}


{% block content %}
<div class="container">
    <h1>Enter new password</h1>
    <p>

    </p>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn">Reset password</button>
    </form>
</div>
{% endblock %}

main/templates/main/register.html
{% extends 'main/header.html' %}


{% block content %}
		<br><br>
		{% if not display_verify %}
		<form method="POST">
			{% csrf_token %}
			{{ form.as_p }}
			<button class='btn' type='submit'>Register</button>
		</form>
		If you already have an account , <a href='/login'>Login</a> instead. 
		{% else %}
		<form method="POST">
			{% csrf_token %}
			{{ form2.as_p }}
			<button class='btn' type='submit'>Verify</button>
		</form>
		{% endif%}
{% endblock %}

main/templates/main/reset_password_email.html
{% load i18n %}{% autoescape off %}
{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}

{% trans "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% trans "Your username, in case you have forgotten:" %} {{ user.get_username }}

{% trans "Thanks for using our site!" %}

{% blocktrans %}The {{ site_name }} team{% endblocktrans %}

{% endautoescape %}